ci:
  skip: [mypy]

repos:
  - hooks:
      - id: no rej
        name: Check for .rej files
        entry: .rej files found, fix conflicts from these rejected files.
        language: fail
        files: \.rej$
    repo: local
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.14.0'
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
  - hooks:
      - id: codespell
        args:
          - --ignore-words-list
          - ba,datas,fo,uptodate
    repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      files: ^dvc_s3/
      language: system
      types: [python]
